# Generated by Django 2.2.10 on 2020-03-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200302_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desctiption',
            new_name='description',
        ),
    ]
